// IBE Direct Interface Demo - Client
// This demo shows how to use IBE/IBS core API directly
// The client encrypts data and verifies signatures

#include <iostream>
#include <vector>
#include <string>
#include "sm9_ibe.h"
#include "sm9_ibs.h"

// read_file is already defined in io.h (included by sm9_ibe.h)

int main() {
    std::cout << "=== IBE Direct Interface Demo - Client ===" << std::endl;

    const std::string master_pub_file = "sm9_ibe_master.pub";
    const std::string user_id = "user@example.com";

    // ---------- 1. Load master public key ----------
    std::cout << "[Client] Loading IBE master public key..." << std::endl;
    SM9_IBE ibe_sender;
    std::vector<uint8_t> mpk_der;
    if (!read_file(master_pub_file, mpk_der)) {
        std::cerr << "[Client] Failed to read master public key file" << std::endl;
        return 1;
    }
    if (!ibe_sender.load_master_public_der(mpk_der)) {
        std::cerr << "[Client] Failed to load master public key from DER" << std::endl;
        return 1;
    }
    std::cout << "[Client] Master public key loaded" << std::endl;

    // ---------- 2. Encrypt message ----------
    std::cout << "[Client] Encrypting message for: " << user_id << std::endl;
    std::string plaintext = "Hello, SM9 IBE! This is a secret message.";
    std::vector<unsigned char> pt(plaintext.begin(), plaintext.end());
    std::vector<unsigned char> ciphertext;

    if (!ibe_sender.encrypt(user_id, pt, ciphertext)) {
        std::cerr << "[Client] Encryption failed" << std::endl;
        return 1;
    }
    std::cout << "[Client] Ciphertext size: " << ciphertext.size() << " bytes" << std::endl;

    // ---------- 3. Simulate network transmission ----------
    // In real scenario, the client would receive the private key DER from server
    // Here we just read the file that was generated by the server
    std::vector<uint8_t> user_priv_der;
    std::cout << "\n[Client] Simulating network: reading private key from server..." << std::endl;
    // Note: In this demo, we assume the client somehow receives the private key DER
    // In production, this would come via secure channel from PKG

    // ---------- 4. Decrypt message (simulated - in real scenario this would be the receiver) ----------
    std::cout << "[Client] Decryption would happen on receiver side." << std::endl;
    std::cout << "[Client] In this demo, encryption was successful." << std::endl;

    // ---------- 5. IBS Verification Demo ----------
    std::cout << "\n--- IBS Demo ---" << std::endl;
    SM9_IBS ibs_verifier;
    if (!ibs_verifier.load_master_public("sm9_ibs_master.pub")) {
        std::cerr << "[Client] Failed to load IBS master public key" << std::endl;
        return 1;
    }
    std::cout << "[Client] IBS master public key loaded" << std::endl;

    // Sign a message (using IBS user private key file)
    std::cout << "[Client] Signing message..." << std::endl;
    std::vector<uint8_t> ibs_priv_der;
    if (!read_file("sm9_ibs_user.key", ibs_priv_der)) {
        std::cerr << "[Client] Failed to read IBS private key file" << std::endl;
        std::cout << "[Client] Note: IBS private key not available, skipping sign demo" << std::endl;
        return 0;
    }

    std::vector<unsigned char> msg = {'H', 'e', 'l', 'l', 'o', ' ', 'S', 'M', '9'};
    std::vector<uint8_t> signature;
    if (!ibs_verifier.sign_with_der(ibs_priv_der, msg, signature)) {
        std::cerr << "[Client] Signing failed" << std::endl;
        return 1;
    }
    std::cout << "[Client] Signature size: " << signature.size() << " bytes" << std::endl;

    // Verify signature
    std::cout << "[Client] Verifying signature..." << std::endl;
    if (ibs_verifier.verify(user_id, msg, signature)) {
        std::cout << "[Client] IBS verification SUCCESS!" << std::endl;
    } else {
        std::cout << "[Client] IBS verification FAILED!" << std::endl;
    }

    std::cout << "\n[Client] All demos completed." << std::endl;
    return 0;
}
